package com.sgo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AmountInfoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amount_info.amount_info_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer amountInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amount_info.balance
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amount_info.change_time
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amount_info.change_cause
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer changeCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column amount_info.user_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amount_info.amount_info_id
     *
     * @return the value of amount_info.amount_info_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getAmountInfoId() {
        return amountInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amount_info.amount_info_id
     *
     * @param amountInfoId the value for amount_info.amount_info_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setAmountInfoId(Integer amountInfoId) {
        this.amountInfoId = amountInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amount_info.balance
     *
     * @return the value of amount_info.balance
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amount_info.balance
     *
     * @param balance the value for amount_info.balance
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amount_info.change_time
     *
     * @return the value of amount_info.change_time
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amount_info.change_time
     *
     * @param changeTime the value for amount_info.change_time
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amount_info.change_cause
     *
     * @return the value of amount_info.change_cause
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getChangeCause() {
        return changeCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amount_info.change_cause
     *
     * @param changeCause the value for amount_info.change_cause
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setChangeCause(Integer changeCause) {
        this.changeCause = changeCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column amount_info.user_id
     *
     * @return the value of amount_info.user_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column amount_info.user_id
     *
     * @param userId the value for amount_info.user_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}