package com.sgo.entity;

import java.math.BigDecimal;
import java.util.Date;

public class EmployerEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer employerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_age
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_redidential_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerRedidentialAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_birthday
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Date employerBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_contact_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerContactAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_job_number
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerJobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_unsettled_wages
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private BigDecimal employerUnsettledWages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_wages_settled
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private BigDecimal employerWagesSettled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.total_order_amount
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private BigDecimal totalOrderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.skill1
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String skill1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.skill2
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String skill2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.skill3
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String skill3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.engaging_services
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String engagingServices;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.employer_img
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String employerImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.emoliyer_salary
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private BigDecimal emoliyerSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_id
     *
     * @return the value of employer.employer_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getEmployerId() {
        return employerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_id
     *
     * @param employerId the value for employer.employer_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerId(Integer employerId) {
        this.employerId = employerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_name
     *
     * @return the value of employer.employer_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerName() {
        return employerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_name
     *
     * @param employerName the value for employer.employer_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerName(String employerName) {
        this.employerName = employerName == null ? null : employerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_age
     *
     * @return the value of employer.employer_age
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerAge() {
        return employerAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_age
     *
     * @param employerAge the value for employer.employer_age
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerAge(String employerAge) {
        this.employerAge = employerAge == null ? null : employerAge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_phone
     *
     * @return the value of employer.employer_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerPhone() {
        return employerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_phone
     *
     * @param employerPhone the value for employer.employer_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerPhone(String employerPhone) {
        this.employerPhone = employerPhone == null ? null : employerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_redidential_address
     *
     * @return the value of employer.employer_redidential_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerRedidentialAddress() {
        return employerRedidentialAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_redidential_address
     *
     * @param employerRedidentialAddress the value for employer.employer_redidential_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerRedidentialAddress(String employerRedidentialAddress) {
        this.employerRedidentialAddress = employerRedidentialAddress == null ? null : employerRedidentialAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_birthday
     *
     * @return the value of employer.employer_birthday
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Date getEmployerBirthday() {
        return employerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_birthday
     *
     * @param employerBirthday the value for employer.employer_birthday
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerBirthday(Date employerBirthday) {
        this.employerBirthday = employerBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_gender
     *
     * @return the value of employer.employer_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerGender() {
        return employerGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_gender
     *
     * @param employerGender the value for employer.employer_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerGender(String employerGender) {
        this.employerGender = employerGender == null ? null : employerGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_contact_address
     *
     * @return the value of employer.employer_contact_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerContactAddress() {
        return employerContactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_contact_address
     *
     * @param employerContactAddress the value for employer.employer_contact_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerContactAddress(String employerContactAddress) {
        this.employerContactAddress = employerContactAddress == null ? null : employerContactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_job_number
     *
     * @return the value of employer.employer_job_number
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerJobNumber() {
        return employerJobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_job_number
     *
     * @param employerJobNumber the value for employer.employer_job_number
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerJobNumber(String employerJobNumber) {
        this.employerJobNumber = employerJobNumber == null ? null : employerJobNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_unsettled_wages
     *
     * @return the value of employer.employer_unsettled_wages
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public BigDecimal getEmployerUnsettledWages() {
        return employerUnsettledWages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_unsettled_wages
     *
     * @param employerUnsettledWages the value for employer.employer_unsettled_wages
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerUnsettledWages(BigDecimal employerUnsettledWages) {
        this.employerUnsettledWages = employerUnsettledWages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_wages_settled
     *
     * @return the value of employer.employer_wages_settled
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public BigDecimal getEmployerWagesSettled() {
        return employerWagesSettled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_wages_settled
     *
     * @param employerWagesSettled the value for employer.employer_wages_settled
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerWagesSettled(BigDecimal employerWagesSettled) {
        this.employerWagesSettled = employerWagesSettled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.total_order_amount
     *
     * @return the value of employer.total_order_amount
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public BigDecimal getTotalOrderAmount() {
        return totalOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.total_order_amount
     *
     * @param totalOrderAmount the value for employer.total_order_amount
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setTotalOrderAmount(BigDecimal totalOrderAmount) {
        this.totalOrderAmount = totalOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.skill1
     *
     * @return the value of employer.skill1
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getSkill1() {
        return skill1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.skill1
     *
     * @param skill1 the value for employer.skill1
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setSkill1(String skill1) {
        this.skill1 = skill1 == null ? null : skill1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.skill2
     *
     * @return the value of employer.skill2
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getSkill2() {
        return skill2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.skill2
     *
     * @param skill2 the value for employer.skill2
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setSkill2(String skill2) {
        this.skill2 = skill2 == null ? null : skill2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.skill3
     *
     * @return the value of employer.skill3
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getSkill3() {
        return skill3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.skill3
     *
     * @param skill3 the value for employer.skill3
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setSkill3(String skill3) {
        this.skill3 = skill3 == null ? null : skill3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.engaging_services
     *
     * @return the value of employer.engaging_services
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEngagingServices() {
        return engagingServices;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.engaging_services
     *
     * @param engagingServices the value for employer.engaging_services
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEngagingServices(String engagingServices) {
        this.engagingServices = engagingServices == null ? null : engagingServices.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.employer_img
     *
     * @return the value of employer.employer_img
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getEmployerImg() {
        return employerImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.employer_img
     *
     * @param employerImg the value for employer.employer_img
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerImg(String employerImg) {
        this.employerImg = employerImg == null ? null : employerImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.emoliyer_salary
     *
     * @return the value of employer.emoliyer_salary
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public BigDecimal getEmoliyerSalary() {
        return emoliyerSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.emoliyer_salary
     *
     * @param emoliyerSalary the value for employer.emoliyer_salary
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmoliyerSalary(BigDecimal emoliyerSalary) {
        this.emoliyerSalary = emoliyerSalary;
    }
}