package com.sgo.entity;

import java.math.BigDecimal;

public class HireEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer hireId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String hireName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String hirePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String hireAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_card
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String hireCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_img
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String hireImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_email
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String hireEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String hireGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hire_.hire_amount
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private BigDecimal hireAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_id
     *
     * @return the value of hire_.hire_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getHireId() {
        return hireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_id
     *
     * @param hireId the value for hire_.hire_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireId(Integer hireId) {
        this.hireId = hireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_name
     *
     * @return the value of hire_.hire_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getHireName() {
        return hireName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_name
     *
     * @param hireName the value for hire_.hire_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireName(String hireName) {
        this.hireName = hireName == null ? null : hireName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_phone
     *
     * @return the value of hire_.hire_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getHirePhone() {
        return hirePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_phone
     *
     * @param hirePhone the value for hire_.hire_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHirePhone(String hirePhone) {
        this.hirePhone = hirePhone == null ? null : hirePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_address
     *
     * @return the value of hire_.hire_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getHireAddress() {
        return hireAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_address
     *
     * @param hireAddress the value for hire_.hire_address
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireAddress(String hireAddress) {
        this.hireAddress = hireAddress == null ? null : hireAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_card
     *
     * @return the value of hire_.hire_card
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getHireCard() {
        return hireCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_card
     *
     * @param hireCard the value for hire_.hire_card
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireCard(String hireCard) {
        this.hireCard = hireCard == null ? null : hireCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_img
     *
     * @return the value of hire_.hire_img
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getHireImg() {
        return hireImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_img
     *
     * @param hireImg the value for hire_.hire_img
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireImg(String hireImg) {
        this.hireImg = hireImg == null ? null : hireImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_email
     *
     * @return the value of hire_.hire_email
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getHireEmail() {
        return hireEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_email
     *
     * @param hireEmail the value for hire_.hire_email
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireEmail(String hireEmail) {
        this.hireEmail = hireEmail == null ? null : hireEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_gender
     *
     * @return the value of hire_.hire_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getHireGender() {
        return hireGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_gender
     *
     * @param hireGender the value for hire_.hire_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireGender(String hireGender) {
        this.hireGender = hireGender == null ? null : hireGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hire_.hire_amount
     *
     * @return the value of hire_.hire_amount
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public BigDecimal getHireAmount() {
        return hireAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hire_.hire_amount
     *
     * @param hireAmount the value for hire_.hire_amount
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireAmount(BigDecimal hireAmount) {
        this.hireAmount = hireAmount;
    }
}