package com.sgo.entity;

import java.util.Date;

public class OrderEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_price
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String orderPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_start_rtime
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Date orderStartRtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_end_time
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Date orderEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_type
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.order_pay_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer orderPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.employer_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer employerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.hire_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer hireId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_id
     *
     * @return the value of order_.order_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_id
     *
     * @param orderId the value for order_.order_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_status
     *
     * @return the value of order_.order_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_status
     *
     * @param orderStatus the value for order_.order_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_price
     *
     * @return the value of order_.order_price
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_price
     *
     * @param orderPrice the value for order_.order_price
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setOrderPrice(String orderPrice) {
        this.orderPrice = orderPrice == null ? null : orderPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_start_rtime
     *
     * @return the value of order_.order_start_rtime
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Date getOrderStartRtime() {
        return orderStartRtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_start_rtime
     *
     * @param orderStartRtime the value for order_.order_start_rtime
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setOrderStartRtime(Date orderStartRtime) {
        this.orderStartRtime = orderStartRtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_end_time
     *
     * @return the value of order_.order_end_time
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Date getOrderEndTime() {
        return orderEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_end_time
     *
     * @param orderEndTime the value for order_.order_end_time
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setOrderEndTime(Date orderEndTime) {
        this.orderEndTime = orderEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_type
     *
     * @return the value of order_.order_type
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_type
     *
     * @param orderType the value for order_.order_type
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.order_pay_status
     *
     * @return the value of order_.order_pay_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.order_pay_status
     *
     * @param orderPayStatus the value for order_.order_pay_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setOrderPayStatus(Integer orderPayStatus) {
        this.orderPayStatus = orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.employer_id
     *
     * @return the value of order_.employer_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getEmployerId() {
        return employerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.employer_id
     *
     * @param employerId the value for order_.employer_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setEmployerId(Integer employerId) {
        this.employerId = employerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.hire_id
     *
     * @return the value of order_.hire_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getHireId() {
        return hireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.hire_id
     *
     * @param hireId the value for order_.hire_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setHireId(Integer hireId) {
        this.hireId = hireId;
    }
}