package com.sgo.entity;

public class ProvinceEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.province_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String provinceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_id
     *
     * @return the value of province.province_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_id
     *
     * @param provinceId the value for province.province_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.province_name
     *
     * @return the value of province.province_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.province_name
     *
     * @param provinceName the value for province.province_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }
}