package com.sgo.entity;

import java.math.BigDecimal;

public class UserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_password
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Long userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_card
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_role
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_adress
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_salary
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private BigDecimal userSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_grade
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer userGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_skill
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userSkill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_credit
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer userCredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_experience
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer userExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_age
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_.user_account_money
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    private String userAccountMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_id
     *
     * @return the value of user_.user_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_id
     *
     * @param userId the value for user_.user_id
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_name
     *
     * @return the value of user_.user_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_name
     *
     * @param userName the value for user_.user_name
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_password
     *
     * @return the value of user_.user_password
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_password
     *
     * @param userPassword the value for user_.user_password
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_phone
     *
     * @return the value of user_.user_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_phone
     *
     * @param userPhone the value for user_.user_phone
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_card
     *
     * @return the value of user_.user_card
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserCard() {
        return userCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_card
     *
     * @param userCard the value for user_.user_card
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserCard(String userCard) {
        this.userCard = userCard == null ? null : userCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_role
     *
     * @return the value of user_.user_role
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_role
     *
     * @param userRole the value for user_.user_role
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_adress
     *
     * @return the value of user_.user_adress
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserAdress() {
        return userAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_adress
     *
     * @param userAdress the value for user_.user_adress
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserAdress(String userAdress) {
        this.userAdress = userAdress == null ? null : userAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_salary
     *
     * @return the value of user_.user_salary
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public BigDecimal getUserSalary() {
        return userSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_salary
     *
     * @param userSalary the value for user_.user_salary
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserSalary(BigDecimal userSalary) {
        this.userSalary = userSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_grade
     *
     * @return the value of user_.user_grade
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getUserGrade() {
        return userGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_grade
     *
     * @param userGrade the value for user_.user_grade
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserGrade(Integer userGrade) {
        this.userGrade = userGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_status
     *
     * @return the value of user_.user_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_status
     *
     * @param userStatus the value for user_.user_status
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_skill
     *
     * @return the value of user_.user_skill
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserSkill() {
        return userSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_skill
     *
     * @param userSkill the value for user_.user_skill
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserSkill(String userSkill) {
        this.userSkill = userSkill == null ? null : userSkill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_credit
     *
     * @return the value of user_.user_credit
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getUserCredit() {
        return userCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_credit
     *
     * @param userCredit the value for user_.user_credit
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserCredit(Integer userCredit) {
        this.userCredit = userCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_experience
     *
     * @return the value of user_.user_experience
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getUserExperience() {
        return userExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_experience
     *
     * @param userExperience the value for user_.user_experience
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserExperience(Integer userExperience) {
        this.userExperience = userExperience;
    }

    @Override
    public String toString() {
        return "UserEntity{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                ", userPhone=" + userPhone +
                ", userCard='" + userCard + '\'' +
                ", userRole='" + userRole + '\'' +
                ", userAdress='" + userAdress + '\'' +
                ", userSalary=" + userSalary +
                ", userGrade=" + userGrade +
                ", userStatus='" + userStatus + '\'' +
                ", userSkill='" + userSkill + '\'' +
                ", userCredit=" + userCredit +
                ", userExperience=" + userExperience +
                ", userAge=" + userAge +
                ", userGender='" + userGender + '\'' +
                ", userAccountMoney='" + userAccountMoney + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_age
     *
     * @return the value of user_.user_age
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_age
     *
     * @param userAge the value for user_.user_age
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_gender
     *
     * @return the value of user_.user_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_gender
     *
     * @param userGender the value for user_.user_gender
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserGender(String userGender) {
        this.userGender = userGender == null ? null : userGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_.user_account_money
     *
     * @return the value of user_.user_account_money
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public String getUserAccountMoney() {
        return userAccountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_.user_account_money
     *
     * @param userAccountMoney the value for user_.user_account_money
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    public void setUserAccountMoney(String userAccountMoney) {
        this.userAccountMoney = userAccountMoney == null ? null : userAccountMoney.trim();
    }
}