package com.sgo.mappers;

import com.sgo.entity.AmountInfoEntity;

import java.util.List;

public interface AmountInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amount_info
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int deleteByPrimaryKey(Integer amountInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amount_info
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int insert(AmountInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amount_info
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    AmountInfoEntity selectByPrimaryKey(Integer amountInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amount_info
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    List<AmountInfoEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table amount_info
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int updateByPrimaryKey(AmountInfoEntity record);
}