package com.sgo.mappers;

import com.sgo.entity.CityEntity;

import java.util.List;

public interface CityEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    int insert(CityEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    CityEntity selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    List<CityEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbggenerated Wed Sep 21 21:51:13 CST 2022
     */
    int updateByPrimaryKey(CityEntity record);
}