package com.sgo.mappers;

import com.sgo.entity.EmployerEntity;

import java.util.List;

public interface EmployerEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employer
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int deleteByPrimaryKey(Integer employerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employer
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int insert(EmployerEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employer
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    EmployerEntity selectByPrimaryKey(Integer employerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employer
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    List<EmployerEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employer
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int updateByPrimaryKey(EmployerEntity record);
}