package com.sgo.mappers;

import com.sgo.entity.HireEntity;

import java.util.List;

public interface HireEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hire_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int deleteByPrimaryKey(Integer hireId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hire_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int insert(HireEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hire_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    HireEntity selectByPrimaryKey(Integer hireId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hire_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    List<HireEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hire_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int updateByPrimaryKey(HireEntity record);
}