package com.sgo.mappers;

import com.sgo.entity.ProvinceEntity;

import java.util.List;

public interface ProvinceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int deleteByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int insert(ProvinceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    ProvinceEntity selectByPrimaryKey(Integer provinceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    List<ProvinceEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int updateByPrimaryKey(ProvinceEntity record);
}