package com.sgo.mappers;

import com.sgo.entity.UserEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    UserEntity selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    List<UserEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_
     *
     * @mbggenerated Wed Sep 21 21:49:32 CST 2022
     */
    int updateByPrimaryKey(UserEntity record);

    UserEntity login(@Param(value = "phone") String phone,
                     @Param(value = "password")String password,
                     @Param(value = "role")String role);

    List<UserEntity> queryUserbyname(@Param(value = "username")String username, @Param(value = "role")String role);

    List<UserEntity> queryUserByphone(@Param(value = "phone")String phone, @Param(value = "role")String role);

    Integer registerUser(@Param("u") UserEntity userEntity);

    List<UserEntity> queryUserByCard(@Param("usercard") String usercard, @Param("role") String role);
}